### ISSUE TITLE
Update Install Instructions

### ISSUE THREAD

**Issue by wyhinton** [lex-ikoon/qq#3]
Hello! Wonderful tools. 

Just wondering if we might get an updated installation directions? Looks like they haven't been updated since H16.5, which I believe handled packages differently than newer houdini versions (usually we make at .json files in the packages folder). 

I created a ```qq.json``` file in my packages directory:
```json
{
	"env": [
        {
			"QQ": "C:\Users\Primary User\Desktop\qq-master"
        }
	],
	"path": [
        "$QQ"
    ]
}

```
And all of the toolshelves and tab tools appear. However I dont think the python is getting installed correctly. When I use the `wf_network_ui>replace` tool, I get a `ModuleNotFoundError`:

![image](https://user-images.githubusercontent.com/38958118/193913998-c7f701d3-ef5d-4b21-944d-e43d7868964b.png)

EDIT:

Directly copying and pasting the contents of `qq-master/python3.9libs` into `houdini/python3.7libs` seems to have done the trick :)

**Comment by lex-ikoon** [comment]
Hello, thank you! I have uploaded the .json
